name: prism
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  fluttermoji: ^1.0.2
  #image_cropper: ^5.0.0
  image_picker: ^1.1.2
  image_picker_web: ^2.0.0
  image_editor_plus: 0.2.6
  path_provider: ^2.1.5
  html: ^0.15.0 
  intl: ^0.20.2
  shared_preferences: ^2.5.1
  image: ^4.0.15 
  photo_view: ^0.14.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  http: ^0.13.3
  file_picker: ^9.0.2
  photo_editor_sdk: ^3.2.0
  universal_html: ^2.2.4
  image_gallery_saver: ^1.7.1
  gallery_saver: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/default1.png
    - assets/images/default2.png
    - assets/images/default3.png
